---

- name: reload unit
  become: true
  systemd:
    state: restarted
    daemon_reload: true

- name: restart Nexus
  service:
    name: nexus
    state: restarted

- name: start Nexus
  service:
    name: nexus
    state: started
