---

- name: reload unit
  become: true
  command: systemctl daemon-reload

- name: restart nexus
  service:
    name: nexus
    state: restarted

- name: start nexus
  service:
    name: nexus
    state: started
